# Generated by Django 6.0.2 on 2026-02-16 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('service_type', models.CharField(choices=[('dp', 'DP'), ('terapi', 'Terapi'), ('pas', 'PAS')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('billing_date', models.DateField()),
                ('status', models.BooleanField(default=False)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branches.branch')),
            ],
        ),
    ]
