# Generated by Django 6.0.2 on 2026-02-16 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date', models.DateField()),
                ('bank_origin', models.CharField(max_length=50)),
                ('bank_destination', models.CharField(default='BCA Pusat', max_length=50)),
                ('sender_name', models.CharField(max_length=100)),
                ('transaction_type', models.CharField(choices=[('inflow', 'Pemasukan (Tagihan Murid)'), ('outflow_payroll', 'Pengeluaran (Gaji Terapis)'), ('outflow_sharing', 'Setoran Pusat (Profit Sharing)')], max_length=20)),
                ('proof_of_payment', models.ImageField(blank=True, upload_to='receipts/')),
                ('verified_by_pusat', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('billing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billings.billing')),
            ],
        ),
    ]
