# Generated by Django 6.0.2 on 2026-02-16 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('therapist_name', models.CharField(max_length=100)),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('meal_allowance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bpjs', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_sent', models.BooleanField(default=False)),
            ],
        ),
    ]
